"""empty message

Revision ID: 0e388ba6bb6e
Revises: 600238b3fa6f
Create Date: 2024-01-14 22:18:47.768389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e388ba6bb6e'
down_revision = '600238b3fa6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.drop_column('incident')

    # ### end Alembic commands ###
