"""empty message

Revision ID: 1b28048f60d6
Revises: 0e388ba6bb6e
Create Date: 2024-01-14 22:48:20.641840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b28048f60d6'
down_revision = '0e388ba6bb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perception', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.drop_column('perception')

    # ### end Alembic commands ###
