"""empty message

Revision ID: 3abb293ea024
Revises: 5fced4948ec9
Create Date: 2024-01-15 00:28:28.615042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abb293ea024'
down_revision = '5fced4948ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schools', sa.String(), nullable=True))
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('schools')

    # ### end Alembic commands ###
