"""empty message

Revision ID: 5fced4948ec9
Revises: 5ffb92a0e769
Create Date: 2024-01-15 00:24:03.543317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fced4948ec9'
down_revision = '5ffb92a0e769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.drop_column('school')

    # ### end Alembic commands ###
