"""empty message

Revision ID: 5ffb92a0e769
Revises: 1b28048f60d6
Create Date: 2024-01-14 23:29:22.601879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffb92a0e769'
down_revision = '1b28048f60d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('witness', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_query', schema=None) as batch_op:
        batch_op.drop_column('witness')

    # ### end Alembic commands ###
