"""first

Revision ID: 600238b3fa6f
Revises: 
Create Date: 2024-01-12 12:25:45.849095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600238b3fa6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_entry')
    op.drop_table('search_query')
    # ### end Alembic commands ###
