"""empty message

Revision ID: 98a61638d3e2
Revises: 3abb293ea024
Create Date: 2024-03-12 01:08:48.837285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a61638d3e2'
down_revision = '3abb293ea024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_entry', schema=None) as batch_op:
        batch_op.drop_column('situation')

    # ### end Alembic commands ###
